### ISSUE TITLE
Trouble setting up BlazorMaterialSymbols in .NET MAUI project

### ISSUE THREAD

**Issue by koddek** [mrRundgren/BlazorMaterialSymbols#2]
I’ve been trying to use the BlazorMaterialSymbols library in a .NET MAUI project, but I haven’t been able to get it to work. I’m not sure if I’m setting it up correctly, as there isn’t a clear getting started guide that explains what to put where.

I’ve attached screenshots of my setup and the resulting output in the app. Could you please take a look and let me know if I’m missing something or if there are any additional steps I need to take to get it working?

Thank you for your help!

## What the app shows:
![Screenshot 2023-05-08 at 12 43 25 PM](https://user-images.githubusercontent.com/33549928/236883238-edfa1cde-d249-401e-a700-177a1ab1a714.png)

## MainLayout.razor:
![Screenshot 2023-05-08 at 12 43 00 PM](https://user-images.githubusercontent.com/33549928/236883242-3d182ba8-8e0c-4aec-9f2c-1dda4147d69c.png)

## Page.razor:
![Screenshot 2023-05-08 at 12 42 27 PM](https://user-images.githubusercontent.com/33549928/236883244-ff8bf117-f7de-46f3-9113-f66f95008b1d.png)

**Comment by mrRundgren** [comment]
Hey koddek, thanks for reaching out again.

It looks correct, the way hou set it up. It might be that one of the later version somehow broke MAUI support, ill have to run some test on It.

**Comment by mrRundgren** [comment]
The Installation instructions are somewhat covered here: https://mrrundgren.github.io/IconsAndStuff/ which is also a pretty good partner application to find icons you like/want/need.

Click on title of the window to search, the pull out meny in the far upper right corner allows you to do some settings, and if you click an icon in the main window it will copy the code needed to use it to your clipboard.

The reason why i didnt write anymore than what is shown if you open the right pull out meny on that site is, well there is nothing more to it than is covered there, as long as you use it in a Blazor webassembly or Blazor server app. The MAUI scenario turns out is almost as simple.

So i have confirmed it not working as intended in a MAUI app, it has something to do with using a HeadOutlet way to make blazor write the css and fonts needed to the index.html <head> tag.

So the solution, has nothing to do with the package itself, but rather how hybrid MAUI works:

![image](https://github.com/mrRundgren/BlazorMaterialSymbols/assets/47566445/674a4ab3-2f19-4638-b06b-cfa6d76b1412)

The lines surrounded by red (sorry for my less then fantastic artistic skills :D), needs to be added to your MainPage.xaml file.

After adding that, i get the icons to render:

![image](https://github.com/mrRundgren/BlazorMaterialSymbols/assets/47566445/6d698c8e-7720-4156-b4c7-b57cfe58dc39)

Technically what I am doing is mimicing what blazor WASM and blazzor server does, to allow to use the HeadContent tag to manipulate the index.html's head tag content.

**Comment by mrRundgren** [comment]
Oh while i remember, as a bonus here is where i found the solution to it:

https://github.com/dotnet/maui/issues/12338
